# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Augarten Gold
tagline: 'Imkerei im Augarten Wien'
email: imkermeister@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Berichte und Informationen zur Schau-Imkerei im Augarten Wien. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AbererEugen
github_username:  augartengold

author:
  name: 'Eugen Aberer'
  url:  https://twitter.com/AbererEugen

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Build settings
markdown: kramdown

#theme: jekyll-theme-hydeout

remote_theme: fongandrew/hydeout
#remote-theme: fongandrew/jekyll-theme-hydeout

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom vars
# version:            3.5.3
sidebar_home_link:  true
sidebar_blog_link:  '/blog'     # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
#github:
# repo: https://github.com/augartengold

# google_analytics: UA-117283278-1
